spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pet_sistema
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/pet_sistema
    redis:
      host: localhost
      port: 6379
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  security:
    jwt:
      secret-key: ${JWT_SECRET:chave-secreta-padrao-deve-ser-alterada-em-producao}
      expiration: 86400000 # 24 horas
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    
logging:
  level:
    com.ifcolab.pet_sistema_backend: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO 

app:
  certificado:
    url-validacao: http://localhost:8080/api/v1/certificados/validar/ 