spring.application.name=pet-sistema
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vitorsergio.ts@gmail.com
spring.mail.password=tbzm jdtf yosi vkfo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
